name: Build and Push Docker Image to Docker Hub

on: 
  push:
    tags:
      - '*'

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          target: apache
          build-args: |
            NEXTCLOUD_VERSION=${{github.env.GITHUB_REF_NAME}}
          push: true
          tags: saschanockel/nextcloud:${{github.env.GITHUB_REF_NAME}}-apache
